FeedTN/Models/MenuItem.cs
using System.ComponentModel.DataAnnotations;

namespace FeedTN.Models
{
    public class MenuItem
    {
        [Key]

        public int MenuItemId { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string ImagePath { get; set; }

        public int FavoriteCount { get; set; }

        public bool Active { get; set; }

        public bool GlutenFree { get; set; }

        public bool Vegetarian { get; set; }

        public bool Vegan { get; set; }
    }
}

FeedTN/Models/MenuItemViewModels/MenuItemViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FeedTN.Models.MenuItemViewModels
{
    public class MenuItemViewModel
    {
        public MenuItem MenuItem { get; set; }
        public IFormFile ImageFile { get; set; }
        public bool UserHasFavorited { get; set; }
    }
}

FeedTN/Controllers/FavoritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FeedTN.Data;
using FeedTN.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FeedTN.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FavoritesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Favorites
        public ActionResult Index()
        {
            return View();
        }

        // GET: Favorites/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Favorites/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Favorites/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Favorite favorite)
        {
            try
            {
                var user = await GetCurrentUserAsync();

                var likedMenuItem = await _context.MenuItem
                    .Where(mi => mi.MenuItemId == favorite.MenuItem.MenuItemId)
                    .FirstOrDefaultAsync();

                likedMenuItem.FavoriteCount++;

                _context.MenuItem.Update(likedMenuItem);
                await _context.SaveChangesAsync();

                var favoriteInstance = new Favorite
                {
                    MenuItemId = favorite.MenuItem.MenuItemId
                };

                favoriteInstance.UserId = user.Id;

                _context.Favorite.Add(favoriteInstance);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "MenuItems", new { id = favorite.MenuItem.MenuItemId });
            }
            catch
            {
                return View();
            }
        }

        // GET: Favorites/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Favorites/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Favorites/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Favorites/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Favorite unfavorite)
        {
            try
            {
                var user = await GetCurrentUserAsync();

                var UnlikedMenuItem = await _context.MenuItem
                    .Where(mi => mi.MenuItemId == unfavorite.MenuItem.MenuItemId)
                    .FirstOrDefaultAsync();

                UnlikedMenuItem.FavoriteCount--;

                _context.MenuItem.Update(UnlikedMenuItem);
                await _context.SaveChangesAsync();

                var FavoriteToDelete = await _context.Favorite
                    .Where(f => f.MenuItemId == unfavorite.MenuItem.MenuItemId)
                    .Where(f => f.UserId == user.Id)
                    .FirstOrDefaultAsync();

                _context.Favorite.Remove(FavoriteToDelete);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "MenuItems", new { id = unfavorite.MenuItem.MenuItemId });
            }
            catch
            {
                return View();
            }
        }

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);
    }
}

FeedTN/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FeedTN.Data;
using FeedTN.Models;
using FeedTN.Models.MenuItemViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FeedTN.Controllers
{
    public class MenuItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public MenuItemsController(ApplicationDbContext ctx, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _context = ctx;
        }

        // GET: MenuItems
        public async Task<ActionResult> Index(string filter)
        {
            var menuItems = await _context.MenuItem
                .ToListAsync();
            
            switch (filter)
            {
                case "Gluten Free":
                    menuItems = await _context.MenuItem
                        .Where(mi => mi.GlutenFree == true)
                        .ToListAsync();
                    break;

                case "Vegetarian":
                    menuItems = await _context.MenuItem
                        .Where(mi => mi.Vegetarian == true)
                        .ToListAsync();
                    break;

                case "Vegan":
                    menuItems = await _context.MenuItem
                        .Where(mi => mi.Vegan == true)
                        .ToListAsync();
                    break;

                default:
                    menuItems = await _context.MenuItem
                        .ToListAsync();
                    break;
            }

            return View(menuItems);
        }

        // GET: MenuItems/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var menuItem = await _context.MenuItem
                .FirstOrDefaultAsync(mi => mi.MenuItemId == id);

            var viewModel = new MenuItemViewModel()
            {
                MenuItem = new MenuItem()
            };

            viewModel.MenuItem.MenuItemId = menuItem.MenuItemId;
            viewModel.MenuItem.Title = menuItem.Title;
            viewModel.MenuItem.Description = menuItem.Description;
            viewModel.MenuItem.ImagePath = menuItem.ImagePath;
            viewModel.MenuItem.Active = menuItem.Active;
            viewModel.MenuItem.FavoriteCount = menuItem.FavoriteCount;
            viewModel.MenuItem.GlutenFree = menuItem.GlutenFree;
            viewModel.MenuItem.Vegetarian = menuItem.Vegetarian;
            viewModel.MenuItem.Vegan = menuItem.Vegan;

            if (_signInManager.IsSignedIn(User))
            {
                var user = await GetCurrentUserAsync();

                var userPreference = await _context.Favorite
                    .Where(p => p.MenuItemId == id)
                    .Where(p => p.UserId == user.Id)
                    .FirstOrDefaultAsync();

                if (userPreference == null)
                {
                    viewModel.UserHasFavorited = false;
                } else
                {
                    viewModel.UserHasFavorited = true;
                }

                return View(viewModel);
            }

            return View(viewModel);
        }

        // GET: MenuItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MenuItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MenuItemViewModel menuItemViewModel)
        {
            try
            {
                var menuItem = new MenuItem
                {
                    Title = menuItemViewModel.MenuItem.Title,
                    Description = menuItemViewModel.MenuItem.Description,
                    FavoriteCount = menuItemViewModel.MenuItem.FavoriteCount,
                    Active = menuItemViewModel.MenuItem.Active,
                    GlutenFree = menuItemViewModel.MenuItem.GlutenFree,
                    Vegetarian = menuItemViewModel.MenuItem.Vegetarian,
                    Vegan = menuItemViewModel.MenuItem.Vegan
                };

                var uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images");
                if (menuItemViewModel.ImageFile != null)
                {
                    var fileName = Guid.NewGuid().ToString() + menuItemViewModel.ImageFile.FileName;
                    menuItem.ImagePath = fileName;
                    using (var fileStream = new FileStream(Path.Combine(uploadPath, fileName), FileMode.Create))
                    {
                        await menuItemViewModel.ImageFile.CopyToAsync(fileStream);
                    }
                }

                _context.MenuItem.Add(menuItem);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuItems/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var menuItem = await _context.MenuItem.FirstOrDefaultAsync(mi => mi.MenuItemId == id);

            return View(menuItem);
        }

        // POST: MenuItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MenuItem menuItem)
        {
            try
            {
                var menuItemItem = new MenuItem()
                {
                    MenuItemId = menuItem.MenuItemId,
                    Title = menuItem.Title,
                    Description = menuItem.Description,
                    ImagePath = menuItem.ImagePath,
                    FavoriteCount = menuItem.FavoriteCount,
                    Active = menuItem.Active,
                    GlutenFree = menuItem.GlutenFree,
                    Vegetarian = menuItem.Vegetarian,
                    Vegan = menuItem.Vegan
                };

                _context.MenuItem.Update(menuItemItem);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);
    }
}

FeedTN/Controllers/UserMenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FeedTN.Data;
using FeedTN.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Schema;

namespace FeedTN.Controllers
{
    public class UserMenuItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserMenuItemsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: UserMenuItems
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        // POST: UserMenuItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int id)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                var userOpenOrder = _context.Order.Where(o => o.UserId == user.Id).FirstOrDefault(o => o.DateCompleted == null);
                if (userOpenOrder != null)
                {
                    var newUserMenuItem = new UserMenuItem
                    {
                        UserId = userOpenOrder.UserId,
                        MenuItemId = id
                    };

                    userOpenOrder.UserMenuItems = new List<UserMenuItem>();

                    userOpenOrder.UserMenuItems.Add(newUserMenuItem);

                    _context.UserMenuItem.Add(newUserMenuItem);

                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index", "MenuItems");

                } else
                {
                    var newOrder = new Order
                    {
                        UserId = user.Id,
                        DateCreated = DateTime.Now,
                        UserMenuItems = new List<UserMenuItem>()
                    };

                    var newUserMenuItem = new UserMenuItem
                    {
                        UserId = user.Id,
                        MenuItemId = id
                    };

                    newOrder.UserMenuItems.Add(newUserMenuItem);

                    _context.Order.Add(newOrder);
                    _context.UserMenuItem.Add(newUserMenuItem);

                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index", "MenuItems");
                }
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: UserMenuItems/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserMenuItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: UserMenuItems/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var user = await GetCurrentUserAsync();

                var userOrder = await _context.Order
                    .Where(o => o.DateCompleted == null)
                    .Where(o => o.UserId == user.Id)
                    .FirstOrDefaultAsync();

                var userMenuItem = await _context.UserMenuItem
                    .Where(mi => mi.OrderId == userOrder.OrderId)
                    .FirstOrDefaultAsync(mi => mi.MenuItemId == id);

                _context.UserMenuItem.Remove(userMenuItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Orders");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);
    }
}

FeedTN/Views/MenuItems/Create.cshtml
@model FeedTN.Models.MenuItemViewModels.MenuItemViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add a Menu Item</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MenuItem.Title" class="control-label">Title</label>
                <input asp-for="MenuItem.Title" class="form-control" />
                <span asp-validation-for="MenuItem.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuItem.Description" class="control-label">Description</label>
                <textarea asp-for="MenuItem.Description" class="form-control"></textarea>
                <span asp-validation-for="MenuItem.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuItem.Active" class="control-label">Add to Today's Menu</label>
                <input type="checkbox" asp-for="MenuItem.Active" class="form-control" />
                <span asp-validation-for="MenuItem.Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label">Upload an Image</label>
                <input asp-for="ImageFile" class="form-control" type="file"/>
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuItem.Vegetarian" class="control-label">Vegetarian</label>
                <input type="checkbox" asp-for="MenuItem.Vegetarian" class="form-control" />
                <span asp-validation-for="MenuItem.Vegetarian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuItem.Vegan" class="control-label">Vegan</label>
                <input type="checkbox" asp-for="MenuItem.Vegan" class="form-control" />
                <span asp-validation-for="MenuItem.Vegan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuItem.GlutenFree" class="control-label">Gluten Free</label>
                <input type="checkbox" asp-for="MenuItem.GlutenFree" class="form-control" />
                <span asp-validation-for="MenuItem.GlutenFree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FeedTN/Views/MenuItems/Details.cshtml
@using Microsoft.AspNetCore.Identity
@model FeedTN.Models.MenuItemViewModels.MenuItemViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
}

@if (!SignInManager.IsSignedIn(User) || UserManager.GetUserAsync(User).Result.IsAdmin == true)
{
    <div class="row float-right">
        <h4>@Model.MenuItem.FavoriteCount user(s) favorited this</h4>
    </div>
}
else if (Model.UserHasFavorited == false)
{
    <div class="float-right">
        <h4>@Model.MenuItem.FavoriteCount user(s) favorited this</h4>
    </div>
    <div class="float-right">
        <form asp-controller="Favorites" asp-action="Create">
            <input type="hidden" asp-for="@Model.MenuItem.MenuItemId" />
            <input type="submit" value="🤍 Favorite" class="btn" />
        </form>
    </div>
}
else
{
    <div class="float-right">
        <h4>@Model.MenuItem.FavoriteCount user(s) favorited this</h4>
    </div>
    <div class="float-right">
        <form asp-controller="Favorites" asp-action="Delete">
            <input type="hidden" asp-for="@Model.MenuItem.MenuItemId" />
            <input type="submit" value="❤ Unfavorite" class="btn" />
        </form>
    </div>
}

<div>
    <h4>@Html.DisplayFor(model => model.MenuItem.Title)</h4>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <dl class="row">
                <dt class="col-sm-3">
                    Nutrition Facts
                </dt>
                <dd class="col-sm-7">
                    @Html.DisplayFor(model => model.MenuItem.Description)
                </dd>
                <dt class="col-sm-3">
                    Gluten Free
                </dt>
                @if (Model.MenuItem.GlutenFree == true)
                {
                    <dd class="col-sm-7">
                        ✔
                    </dd>
                }
                else
                {
                    <dd class="col-sm-7">
                        ❌
                    </dd>
                }
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.MenuItem.Vegetarian)
                </dt>
                @if (Model.MenuItem.Vegetarian == true)
                {
                    <dd class="col-sm-7">
                        ✔
                    </dd>
                }
                else
                {
                    <dd class="col-sm-7">
                        ❌
                    </dd>
                }
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.MenuItem.Vegan)
                </dt>
                @if (Model.MenuItem.Vegan == true)
                {
                    <dd class="col-sm-7">
                        ✔
                    </dd>
                }
                else
                {
                    <dd class="col-sm-7">
                        ❌
                    </dd>
                }
            </dl>
        @if (!SignInManager.IsSignedIn(User) || UserManager.GetUserAsync(User).Result.IsAdmin == true)
        {

        } else
        {
        <form asp-controller="UserMenuItems" asp-action="Create" asp-route-id="@Model.MenuItem.MenuItemId">
            <input type="submit" class="btn btn-primary bg-primary border-primary" value="Add to cart" />
        </form>
        }
        </div>
        <div class="col-md-6">
            <div>
                <img style="max-height: 500px; max-width: 500px" src="~/images/@Model.MenuItem.ImagePath" alt="descriptive image" />
            </div>
        </div>
    </div>
</div>

FeedTN/Views/MenuItems/Edit.cshtml
@model FeedTN.Models.MenuItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> Today's Menu</label>
            </div>
            <input type="hidden" asp-for="MenuItemId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Nutrition Facts</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ImagePath" />
            <input type="hidden" asp-for="FavoriteCount" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GlutenFree" /> Gluten Free
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Vegetarian" /> @Html.DisplayNameFor(model => model.Vegetarian)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Vegan" /> @Html.DisplayNameFor(model => model.Vegan)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}